# -*- coding: utf-8 -*-
"""Model_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11eGIe1QYmnbGwKIQogtyi81yUiC1aa9I
"""

# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""# Image Splicing Detection Using Low-Dimensional Feature Vector of Texture Features and Haralick Features Based on GLCM"""

# Step 2: Set dataset path
# Adjust the path according to where you placed "ImSpliceDataset"
dataset_path = "/content/drive/MyDrive/Sem 7 Folder/Academic Project/ImSpliceDataset/ImSpliceDataset"

# Inspect folders
import os
print("Files in dataset:", os.listdir(dataset_path))

# Step 3: Define Authentic & Spliced directories
# Update names if they differ (sometimes 'Au' and 'Sp' are used instead)
# Collect all authentic and spliced folders
authentic_folders = [os.path.join(dataset_path, f) for f in os.listdir(dataset_path) if f.startswith("Au-")]
spliced_folders   = [os.path.join(dataset_path, f) for f in os.listdir(dataset_path) if f.startswith("Sp-")]

print("Authentic folders:", authentic_folders)
print("Spliced folders:", spliced_folders)



# Step 4: Feature Extraction (GLCM + Haralick)
import numpy as np
from skimage import io, color, feature
from tqdm import tqdm

def extract_glcm_features(image_path, distances=[1], angles=[0, np.pi/4, np.pi/2, 3*np.pi/4]):
    try:
        img = io.imread(image_path)
        if img.ndim == 3:
            gray = color.rgb2gray(img)
        else:
            gray = img
        gray = (gray * 255).astype('uint8')
        glcm = feature.graycomatrix(gray, distances=distances, angles=angles, symmetric=True, normed=True)

        feats = []
        props = ['contrast', 'dissimilarity', 'homogeneity', 'energy', 'correlation', 'ASM']
        for p in props:
            feats.extend(feature.graycoprops(glcm, p).flatten())
        return np.array(feats)
    except Exception as e:
        print("Error processing", image_path, ":", e)
        return None

X, y = [], []

# Authentic images → label 0
for folder in authentic_folders:
    for img in os.listdir(folder):
        feats = extract_glcm_features(os.path.join(folder, img))
        if feats is not None:
            X.append(feats)
            y.append(0)

# Spliced images → label 1
for folder in spliced_folders:
    for img in os.listdir(folder):
        feats = extract_glcm_features(os.path.join(folder, img))
        if feats is not None:
            X.append(feats)
            y.append(1)

X = np.array(X)
y = np.array(y)

print("Feature matrix shape:", X.shape)
print("Labels shape:", y.shape)

# Step 5: Dimensionality Reduction (PCA)
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=20)
X_pca = pca.fit_transform(X_scaled)

print("Reduced feature shape:", X_pca.shape)

# Step 6: Train Classifier (SVM)
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.3, random_state=42, stratify=y)

clf = SVC(kernel='rbf', C=1, gamma='scale')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Step 7: 2D Visualization (PCA)
import matplotlib.pyplot as plt

pca_2d = PCA(n_components=2)
X_vis = pca_2d.fit_transform(X_scaled)

plt.figure(figsize=(8,6))
plt.scatter(X_vis[y==0, 0], X_vis[y==0, 1], color='blue', alpha=0.6, label='Authentic')
plt.scatter(X_vis[y==1, 0], X_vis[y==1, 1], color='red', alpha=0.6, label='Spliced')
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.title("2D PCA Visualization of GLCM-Haralick Features (Columbia/ImSpliceDataset)")
plt.legend()
plt.grid(True)
plt.show()

# Step 8: Plot Confusion Matrix
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Authentic', 'Spliced'])
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for SVM Classifier')
plt.show()